line-length = 120

target-version = "py311"

exclude = [
  "scripts",
  "**/__pycache__",
]

[lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"

